FORMAT: 1A

# API V1

## Group Values

### /api/Values

#### GET

+ Request

    + Headers

            Accept: application/json

    + Body

+ Response 200 (application/json)

    Success

    + Body

            [
              "in cupidatat qui",
              "laborum est ullamco proident",
              "in aute"
            ]

    + Schema

            {
              "type": "array",
              "items": {
                "type": "string"
              }
            }

#### POST

+ Request (application/json)

    + Body

            exercitation

    + Schema

            {
              "type": "string"
            }

+ Response 200

    Success

    + Body

### /api/Values/{id}

#### GET

+ Parameters

    + id (required)

+ Request

    + Headers

            Accept: application/json

    + Body

+ Response 200 (application/json)

    Success

    + Body

            velit occaecat est et anim

    + Schema

            {
              "type": "string"
            }

#### PUT

+ Parameters

    + id (required)

+ Request (application/json)

    + Body

            sit qui

    + Schema

            {
              "type": "string"
            }

+ Response 200

    Success

    + Body

#### DELETE

+ Parameters

    + id (required)

+ Response 200

    Success

    + Body